#
#  ターゲット
#
TARGET = renesas_t1v1
#TARGET = sunny_gpxu2a
#TARGET = renesas_rcar_s4

#
#  コンパイラ
#
COMPILER = GHS
#COMPILER = CCRH

#
#  ターゲット毎の定義
#
ifeq ($(TARGET), renesas_t1v1)
RLIN3_PORT0 = 0
RLIN3_PORT1 = 1
RLIN3_PORT2 = 2
RLIN3_PORT3 = 3
OSTM_CLK_MHZ = 80
endif

ifeq ($(TARGET), sunny_gpxu2a)
RLIN3_PORT0 = 7
RLIN3_PORT1 = 4
RLIN3_PORT2 = 2
RLIN3_PORT3 = 11
OSTM_CLK_MHZ = 80
endif

ifeq ($(TARGET), renesas_rcar_s4)
RLIN3_PORT0 = 7
RLIN3_PORT1 = 5
RLIN3_PORT2 = 3
RLIN3_PORT3 = 1
OSTM_CLK_MHZ = 80
endif
