#コンフィグレータ キーワード定義

CFG_KW_HV	= "HV"
CFG_KW_VM	= "VM"
CFG_KW_TDMA	= "TDMA"
CFG_KW_VCOM	= "VCOM"

CFG_KW_LEADER_CORE			= "LeaderCoreID"
CFG_KW_HOST_ENTRY_MPU		= "NumberOfHostEntryMPU"
CFG_KW_CRAM_USAGE_SIZE		= "CRAMUsageSize"
CFG_KW_HVCALL				= "HVCall"
CFG_KW_NAME					= "Name"
CFG_KW_NUM_ARGS				= "NumberOfArg"
CFG_KW_CORES				= "Cores"
CFG_KW_ID					= "ID"
CFG_KW_SPID					= "SPID"
CFG_KW_STACK_SIZE_HV		= "StackSizeHV"
CFG_KW_STACK_SIZE_HVTW		= "StackSizeHVTW"
CFG_KW_SINGLE_VM_CORE		= "SingleVMCORE"
CFG_KW_MEM_SECTION			= "MemorySection"
CFG_KW_INT					= "Interrupt"
CFG_KW_INT_NO				= "IntNo"
CFG_KW_INT_HANDLER			= "IntHandler"
CFG_KW_INT_PRI				= "Priority"
CFG_KW_INT_EN				= "Enable"

CFG_KW_COREID				= "CoreID"
CFG_KW_RESET_BASE			= "RestBase"
CFG_KW_MEMORY				= "Memory"
CFG_KW_BASE					= "Base"
CFG_KW_SIZE					= "Size"
CFG_KW_TYPE					= "Type"
CFG_KW_SPID_LIST			= "SPIDList"

CFG_KW_SYS_INTERVAL			= "SystemIntervalUS"
CFG_KW_SOM      			= "SystemOperationMode"
CFG_KW_SCHEDULE_TBL			= "ScheduleTable"
CFG_KW_TIMEWIN				= "TimeWindow"
CFG_KW_VMNAME				= "VMName"
CFG_KW_DURATION				= "DurationUS"
CFG_KW_TWTG_INT				= "TwtgIntNo"
CFG_KW_TWTG_INTERVAL		= "TwtgIntInterval"

CFG_KW_STATEVAR				= "StateVariable"
CFG_KW_WRITABLE_VM			= "WritableVM"
CFG_KW_INIT_STATE			= "InitState"

CFG_KW_MSG_QUEUE			= "MessageQueue"
CFG_KW_MAX_SIZE				= "MaximumSize"
CFG_KW_MSG_QUEUE_SIZE		= "MessageQueueSize"
CFG_KW_WRITABLE_VM			= "WritableVM"
CFG_KW_READABLE_VM			= "ReadableVM"

CFG_KW_SHARED_BUF			= "SharedBuffer"
CFG_KW_ACCESIBLE_VM			= "AccesibleVM"

#ターゲット設定
CFG_KW_MCU			= "MCU"
CFG_KW_NUM_CORES	= "NumberOfCores"
CFG_KW_NUM_INTC2	= "NumberOfINTC2Interrupt"
